"""add hourly stats table

Revision ID: 16c62600f0db
Revises: 2a2328312ac8
Create Date: 2026-09-03 03:45:59.323955

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16c62600f0db"
down_revision: str | None = "2a2328312ac8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_hourly_stats",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id", "timestamp"),
    )
    op.create_index(
        "idx_hourly_item_timestamp",
        "item_hourly_stats",
        ["item_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hourly_item_timestamp", table_name="item_hourly_stats")
    op.drop_table("item_hourly_stats")
    # ### end Alembic commands ###
