"""add indexes

Revision ID: 2a2328312ac8
Revises: 7e4f99b23f35
Create Date: 2026-08-29 01:37:01.269106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2328312ac8'
down_revision: Union[str, None] = '7e4f99b23f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_item_daily_stats_item_date', 'item_daily_stats', ['item_id', 'date'], unique=False)
    op.create_index('idx_item_snapshot_updated_at', 'item_snapshot', ['updated_at'], unique=False)
    op.create_index('idx_user_tracked_items_user_id', 'user_tracked_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_tracked_items_user_id', table_name='user_tracked_items')
    op.drop_index('idx_item_snapshot_updated_at', table_name='item_snapshot')
    op.drop_index('idx_item_daily_stats_item_date', table_name='item_daily_stats')
    # ### end Alembic commands ###
