"""add ondelete cascade

Revision ID: 7e4f99b23f35
Revises: effd454ffb9c
Create Date: 2026-08-29 01:35:38.426700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4f99b23f35'
down_revision: Union[str, None] = 'effd454ffb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_daily_stats_item_id_fkey', 'item_daily_stats', type_='foreignkey')
    op.create_foreign_key(None, 'item_daily_stats', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('item_snapshot_item_id_fkey', 'item_snapshot', type_='foreignkey')
    op.create_foreign_key(None, 'item_snapshot', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('price_alerts_item_id_fkey', 'price_alerts', type_='foreignkey')
    op.drop_constraint('price_alerts_user_id_fkey', 'price_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'price_alerts', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'price_alerts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_item_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_tracked_items_item_id_fkey', 'user_tracked_items', type_='foreignkey')
    op.drop_constraint('user_tracked_items_user_id_fkey', 'user_tracked_items', type_='foreignkey')
    op.create_foreign_key(None, 'user_tracked_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tracked_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tracked_items', type_='foreignkey')
    op.drop_constraint(None, 'user_tracked_items', type_='foreignkey')
    op.create_foreign_key('user_tracked_items_user_id_fkey', 'user_tracked_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_tracked_items_item_id_fkey', 'user_tracked_items', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_item_id_fkey', 'subscriptions', 'items', ['item_id'], ['id'])
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'price_alerts', type_='foreignkey')
    op.drop_constraint(None, 'price_alerts', type_='foreignkey')
    op.create_foreign_key('price_alerts_user_id_fkey', 'price_alerts', 'users', ['user_id'], ['id'])
    op.create_foreign_key('price_alerts_item_id_fkey', 'price_alerts', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'item_snapshot', type_='foreignkey')
    op.create_foreign_key('item_snapshot_item_id_fkey', 'item_snapshot', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'item_daily_stats', type_='foreignkey')
    op.create_foreign_key('item_daily_stats_item_id_fkey', 'item_daily_stats', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
